---
- name: Build-server configuration
  hosts: build_host
  become: yes
  vars_files: 
    - vars.yml

  roles: 
    - docker
    - builder

- name: Web-server configuration
  hosts: prod_host
  become: yes

  roles:
    - docker
    - deployer