---
# tasks file for builder
- name: Ensure git is install
  apt: 
    name: git
    state: present 

- name: Ensure Github-repo is clone  
  git:
    repo: https://github.com/BakirovaAsia/Homework7.git
    dest: /home/admin/Homework7
    clone: yes

- name: Ensure in DockerHub is login
  docker_login:
    username: "{{ DockerHub_user }}"
    password: "{{ DockerHub_pass }}"

- name: Ensure Docker image is build
  docker_image:
    name: bakirovaasia/caucuscalculator
    build:
      path: /home/admin/Homework7/multistage
    tag: latest
    push: yes
    source: build
  
  notify:
    - DockerHub logout
